services:
  - type: web
    name: admirerx-bpo-website
    env: static
    buildCommand: npm install && npm run build
    startCommand: npm start
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18
